### ISSUE TITLE
byte 2 bit-shift

### ISSUE THREAD

**Issue by AbeLancs** [flrrth/pico-dht20#1]
https://github.com/flrrth/pico-dht20/blob/83f84b2b984226ef6083730dac4a3930f2282416/dht20/dht20.py#L96

Shouldn't the second byte be shifted by 4 places only?

**Comment by flrrth** [comment]
Hi @AbeLancs, thanks for question. I will have a look at this.

**Comment by flrrth** [comment]
Fixed.

**Comment by flrrth** [comment]
Fixed.
